version: "3"
services:
  elasticsearch:
    logging:
      driver: "none"
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    environment:
      - bootstrap.memory_lock=true
      - cluster.name=docker-cluster
      - cluster.routing.allocation.disk.threshold_enabled=false
      - discovery.type=single-node
      - ES_JAVA_OPTS=-XX:UseAVX=2 -Xms1g -Xmx1g
    ulimits:
      memlock:
        hard: -1
        soft: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - app-subnet
    healthcheck:
      interval: 20s
      retries: 10
      test: curl -s http://localhost:9200/_cluster/health | grep -vq '"status":"red"'

  kibana:
    logging:
      driver: "none"
    image: docker.elastic.co/kibana/kibana:7.10.1
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - 5601:5601
    networks:
      - app-subnet
    healthcheck:
      interval: 10s
      retries: 20
      test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:5601/api/status
  api:
    stdin_open: true
    # tty: true
    networks:
      - app-subnet
    restart: always
    working_dir: /app
    build: .
    command: bundle exec rackup -d -p 9292 -o 0.0.0.0
    volumes:
      - .:/app
      - ~/.bash_history:/root/.bash_history
    ports:
      - 9292:9292
    depends_on:
      - elasticsearch
volumes:
  db:
  esdata:
    driver: local

networks:
  app-subnet:
    driver: bridge